apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ems-processing-services-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi