apiVersion: v1
kind: PersistentVolume
metadata:
  name: ems-user-data-pv
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    # type: Directory
    path: /var/ems/userdata