apiVersion: v1
kind: PersistentVolume
metadata:
  name: ems-processing-services-pv
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    # type: Directory
    path: /var/ems/processes